[deps]
CPLEX = "a076750e-1247-5638-91d2-ce28b192dca0"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
